import { useState } from 'react'
import { api, organizationPath } from '../lib/api.js'
import { useWorkspace } from '../state/WorkspaceContext.jsx'
import { Dialog, EmptyState, ErrorNotice, Field, LoadingRows, Mono, Page, Section, SubmitRow, formatDate, useResource } from '../components/ui.jsx'

async function loadEnvironmentOptions(organizationId){const projects=(await api(organizationPath(organizationId,'/projects'))).projects;const groups=await Promise.all(projects.map(async project=>({project,environments:(await api(organizationPath(organizationId,`/projects/${project.id}/environments`))).environments})));return groups.flatMap(group=>group.environments.map(environment=>({...environment,projectName:group.project.name})))}

export function ApplicationsPage(){const {organizationId}=useWorkspace();const [open,setOpen]=useState(false);const resource=useResource(async()=>{if(!organizationId)return {applications:[],environments:[]};const [applications,environments]=await Promise.all([api(organizationPath(organizationId,'/applications')),loadEnvironmentOptions(organizationId)]);return {applications:applications.applications,environments}},[organizationId]);const environmentNames=Object.fromEntries((resource.data?.environments||[]).map(item=>[item.id,`${item.projectName} / ${item.name}`]));return <Page title="Applications" description="Deployable workload records. Milestone 1 does not execute them." actions={organizationId&&<button className="button primary" onClick={()=>setOpen(true)}>Create application</button>}><ErrorNotice error={resource.error}/><Section title="Registered applications"><table><thead><tr><th>Name</th><th>Environment</th><th>Source</th><th>Image</th><th>Internal port</th><th>Created</th></tr></thead><tbody>{resource.loading?<LoadingRows columns={6}/>:resource.data.applications.length?resource.data.applications.map(item=><tr key={item.id}><td data-label="Name">{item.name}</td><td data-label="Environment">{environmentNames[item.environmentId]||'—'}</td><td data-label="Source">{item.sourceType}</td><td data-label="Image"><Mono>{item.image||'—'}</Mono></td><td data-label="Internal port"><Mono>{item.internalPort||'—'}</Mono></td><td data-label="Created">{formatDate(item.createdAt)}</td></tr>):<tr><td colSpan="6"><EmptyState title="No applications yet">Create an environment before registering an application.</EmptyState></td></tr>}</tbody></table>{resource.data&&<ApplicationForm open={open} onClose={()=>setOpen(false)} environments={resource.data.environments} onSaved={resource.refresh}/>}</Section></Page>}

function ApplicationForm({open,onClose,environments,onSaved}){const {organizationId}=useWorkspace();const [error,setError]=useState('');const [submitting,setSubmitting]=useState(false);const submit=async(event)=>{event.preventDefault();setSubmitting(true);setError('');const values=Object.fromEntries(new FormData(event.currentTarget));const environmentId=values.environmentId;delete values.environmentId;if(values.internalPort)values.internalPort=Number(values.internalPort);else delete values.internalPort;if(!values.image)delete values.image;try{await api(organizationPath(organizationId,`/environments/${environmentId}/applications`),{method:'POST',body:values});await onSaved();onClose()}catch(requestError){setError(requestError.message)}finally{setSubmitting(false)}};return <Dialog title="Create application" open={open} onClose={onClose}>{environments.length?<form className="form-stack" onSubmit={submit}><Field label="Environment"><select name="environmentId" required>{environments.map(item=><option key={item.id} value={item.id}>{item.projectName} / {item.name}</option>)}</select></Field><Field label="Name"><input name="name" required/></Field><Field label="Source type"><select name="sourceType" defaultValue="docker_image"><option value="docker_image">Docker image</option><option value="git_dockerfile">Git + Dockerfile (record only)</option><option value="compose">Docker Compose (record only)</option></select></Field><Field label="Image" hint="Metadata only. Silicon will not pull or run it in this milestone."><input name="image" className="mono"/></Field><Field label="Internal container port"><input name="internalPort" type="number" min="1" max="65535" className="mono"/></Field><ErrorNotice error={error}/><SubmitRow submitting={submitting} onCancel={onClose} label="Create application"/></form>:<EmptyState title="An environment is required">Create an environment before registering an application.</EmptyState>}</Dialog>}
