import { useState } from 'react'
import { api, organizationPath } from '../lib/api.js'
import { useWorkspace } from '../state/WorkspaceContext.jsx'
import { CreateButton, Dialog, EmptyState, ErrorNotice, Field, LoadingRows, Mono, Notice, Page, Section, Status, SubmitRow, formatDate, useResource } from '../components/ui.jsx'

export function DeploymentsPage(){
  const {organizationId}=useWorkspace();const [open,setOpen]=useState(false)
  const resource=useResource(async()=>{if(!organizationId)return {deployments:[],applications:[]};const [deployments,applications]=await Promise.all([api(organizationPath(organizationId,'/deployments')),api(organizationPath(organizationId,'/applications'))]);return {deployments:deployments.deployments,applications:applications.applications}},[organizationId])
  const names=Object.fromEntries((resource.data?.applications||[]).map(item=>[item.id,item.name]))
  return <Page title="Deployments" description="Immutable deployment history with exact source revisions and explicit trigger types." actions={organizationId&&<CreateButton onClick={()=>setOpen(true)}>Create deployment</CreateButton>}><Notice>Manual image deployments and exact-revision GitHub builds enter the same PostgreSQL job runner and DockerRuntimeProvider. Runtime execution requires the local Docker provider to be enabled by the operator.</Notice><ErrorNotice error={resource.error}/><Section title="Deployment history"><table><thead><tr><th>ID</th><th>Application</th><th>Status</th><th>Trigger</th><th>Image / repository</th><th>Revision</th><th>Created</th></tr></thead><tbody>{resource.loading?<LoadingRows columns={7}/>:resource.data.deployments.length?resource.data.deployments.map(item=><tr key={item.id}><td data-label="ID"><Mono>#{item.number}</Mono></td><td data-label="Application">{names[item.applicationId]||'Unknown'}</td><td data-label="Status"><Status value={item.status}/></td><td data-label="Trigger">{item.triggerType||'manual'}</td><td data-label="Image / repository">{item.image||item.repository||item.source||'—'}</td><td data-label="Revision"><Mono>{item.commitSha||item.sourceRevision||'—'}</Mono></td><td data-label="Created">{formatDate(item.createdAt)}</td></tr>):<tr><td colSpan="7"><EmptyState title="No deployments yet">Create one manually or enable GitHub push deployment for an application.</EmptyState></td></tr>}</tbody></table>{resource.data&&<DeploymentForm open={open} onClose={()=>setOpen(false)} applications={resource.data.applications} onSaved={resource.refresh}/>}</Section></Page>
}

function DeploymentForm({open,onClose,applications,onSaved}){const {organizationId}=useWorkspace();const [error,setError]=useState('');const [submitting,setSubmitting]=useState(false);const submit=async(event)=>{event.preventDefault();setSubmitting(true);setError('');const values=Object.fromEntries(new FormData(event.currentTarget));const applicationId=values.applicationId;delete values.applicationId;try{await api(organizationPath(organizationId,`/applications/${applicationId}/deployments`),{method:'POST',body:values});await onSaved();onClose()}catch(requestError){setError(requestError.message)}finally{setSubmitting(false)}};return <Dialog title="Create deployment" open={open} onClose={onClose}>{applications.length?<form className="form-stack" onSubmit={submit}><Field label="Application"><select name="applicationId" required>{applications.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Source"><input name="source" placeholder="registry or repository reference"/></Field><Field label="Exact source revision"><input name="sourceRevision" className="mono" placeholder="commit SHA or digest"/></Field><Field label="Image"><input name="image" className="mono"/></Field><ErrorNotice error={error}/><SubmitRow submitting={submitting} onCancel={onClose} label="Create deployment"/></form>:<EmptyState title="An application is required">Register an application before creating a deployment.</EmptyState>}</Dialog>}
