import { useState } from 'react'
import { ArrowClockwiseIcon, CloudArrowUpIcon, PathIcon, TrashIcon } from '@phosphor-icons/react'
import { api, organizationPath } from '../lib/api.js'
import { useWorkspace } from '../state/WorkspaceContext.jsx'
import { EmptyState, ErrorNotice, Field, LoadingRows, Mono, Page, Section, Status, useResource } from '../components/ui.jsx'

export function DomainsPage() {
  const { organizationId } = useWorkspace(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const resource = useResource(async () => {
    if (!organizationId) return { domains: [], applications: [], servers: [], tunnels: [] }
    const root = organizationPath(organizationId)
    const [domains, applications, servers, tunnels] = await Promise.all([api(`${root}/domains`), api(`${root}/applications`), api(`${root}/servers`), api(`${root}/integrations/cloudflare/tunnels`).catch(() => ({ tunnels: [] }))])
    return { domains: domains.domains, applications: applications.applications, servers: servers.servers, tunnels: tunnels.tunnels }
  }, [organizationId])
  const run = async (work) => { setBusy(true); setError(''); try { await work(); await resource.refresh() } catch (requestError) { setError(requestError.message) } finally { setBusy(false) } }
  const create = (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); const app = values.applicationId; delete values.applicationId; values.targetPort = Number(values.targetPort); run(() => api(organizationPath(organizationId, `/applications/${app}/domains`), { method: 'POST', body: values })) }
  const route = (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); const tunnel = values.tunnelId; delete values.tunnelId; run(() => api(organizationPath(organizationId, `/integrations/cloudflare/tunnels/${tunnel}/routes`), { method: 'POST', body: values })) }
  const serverName = (id) => resource.data?.servers.find((server) => server.id === id)?.name || '—'
  const appName = (id) => resource.data?.applications.find((application) => application.id === id)?.name || '—'
  return <Page title="Domains" description="Provider-independent application origins reconciled through Cloudflare DNS or Tunnel."><ErrorNotice error={resource.error || error} />
    <Section title="Add custom domain"><form className="form-grid" onSubmit={create}><Field label="Application"><select name="applicationId" required>{(resource.data?.applications || []).filter((item) => item.serverId).map((item) => <option value={item.id} key={item.id}>{item.name} · {serverName(item.serverId)}</option>)}</select></Field><Field label="Hostname"><input name="hostname" placeholder="api.example.com" required /></Field><Field label="Target port"><input name="targetPort" type="number" min="1" max="65535" defaultValue="3000" className="mono" required /></Field><Field label="Protocol"><select name="protocol" defaultValue="http"><option value="http">HTTP</option><option value="https">HTTPS</option><option value="tcp">TCP</option></select></Field><Field label="Routing mode"><select name="routingMode" defaultValue="cloudflare_proxied"><option value="dns_only">DNS only</option><option value="cloudflare_proxied">Cloudflare proxied</option><option value="cloudflare_tunnel">Cloudflare Tunnel</option></select></Field><div className="form-actions"><button className="button primary" disabled={busy || !resource.data?.applications.some((item) => item.serverId)}><CloudArrowUpIcon size={16} /><span>Create route</span></button></div></form></Section>
    <Section title="Managed domains"><table><thead><tr><th>Hostname</th><th>Target</th><th>Origin</th><th>Mode</th><th>State</th><th>Actions</th></tr></thead><tbody>{resource.loading ? <LoadingRows columns={6} /> : resource.data.domains.length ? resource.data.domains.map((item) => <tr key={item.id}><td>{item.hostname}</td><td>{appName(item.applicationId)} · {serverName(item.targetServerId)}</td><td><Mono>{item.protocol} :{item.targetPort}</Mono></td><td>{item.routingMode.replaceAll('_', ' ')}</td><td><Status value={item.dnsState} />{item.lastSyncError && <small>{item.lastSyncError}</small>}</td><td><div className="row-actions"><button className="button ghost compact" disabled={busy || item.routingMode === 'cloudflare_tunnel'} onClick={() => run(() => api(organizationPath(organizationId, `/domains/${item.id}/sync`), { method: 'POST' }))}><ArrowClockwiseIcon size={16} /><span>Sync</span></button><button className="button danger compact" disabled={busy} onClick={() => run(() => api(organizationPath(organizationId, `/domains/${item.id}`), { method: 'DELETE' }))}><TrashIcon size={16} /><span>Delete</span></button></div></td></tr>) : <tr><td colSpan="6"><EmptyState title="No domains yet">Assign an application to a server, then add a domain.</EmptyState></td></tr>}</tbody></table></Section>
    {resource.data?.tunnels.some((item) => item.installationStatus === 'installed') && resource.data?.domains.some((item) => item.routingMode === 'cloudflare_tunnel') && <Section title="Tunnel routes" description="The service URL is resolved from the selected application, server, protocol, and port."><form className="form-grid" onSubmit={route}><Field label="Tunnel"><select name="tunnelId">{resource.data.tunnels.filter((item) => item.installationStatus === 'installed').map((item) => <option key={item.id} value={item.id}>{item.name} · {serverName(item.serverId)}</option>)}</select></Field><Field label="Domain"><select name="domainId">{resource.data.domains.filter((item) => item.routingMode === 'cloudflare_tunnel').map((item) => <option key={item.id} value={item.id}>{item.hostname}</option>)}</select></Field><div className="form-actions"><button className="button secondary" disabled={busy}><PathIcon size={16} /><span>Configure route</span></button></div></form></Section>}
  </Page>
}
