import { useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api, organizationPath } from '../lib/api.js'
import { useWorkspace } from '../state/WorkspaceContext.jsx'
import { ConfigurationEditor, ConfirmDeleteDialog, WorkspaceNav } from '../components/Workspace.jsx'
import { CreateButton, Dialog, EmptyState, ErrorNotice, Field, LoadingRows, Mono, Page, Section, Status, SubmitRow, formatDate, useResource } from '../components/ui.jsx'

async function loadGroups(organizationId) {
  const projects = (await api(organizationPath(organizationId, '/projects'))).projects
  return Promise.all(projects.map(async (project) => ({ project, environments: (await api(organizationPath(organizationId, `/projects/${project.id}/environments`))).environments })))
}

export function EnvironmentsPage() {
  const { organizationId } = useWorkspace(); const [open, setOpen] = useState(false)
  const resource = useResource(async () => { if (!organizationId) return { groups: [], applications: [] }; const [groups, applications] = await Promise.all([loadGroups(organizationId), api(organizationPath(organizationId, '/applications'))]); return { groups, applications: applications.applications } }, [organizationId]); const projects = resource.data?.groups.map((item) => item.project) || []
  return <Page title="Environments" description="Configuration and deployment boundaries grouped by project." actions={organizationId && <CreateButton onClick={() => setOpen(true)}>Create environment</CreateButton>}><ErrorNotice error={resource.error} /><Section title="Project environments">{resource.loading ? <table><tbody><LoadingRows /></tbody></table> : resource.data.groups.some((group) => group.environments.length) ? resource.data.groups.map((group) => <div className="resource-group" key={group.project.id}><h3><Link to={`/projects/${group.project.id}`}>{group.project.name}</Link></h3><table><thead><tr><th>Name</th><th>Slug</th><th>Applications</th><th>Created</th></tr></thead><tbody>{group.environments.length ? group.environments.map((item) => <tr key={item.id}><td><Link to={`/projects/${group.project.id}/environments/${item.id}`}>{item.name}</Link></td><td><Mono>{item.slug}</Mono></td><td>{resource.data.applications.filter((application) => application.environmentId === item.id).length}</td><td>{formatDate(item.createdAt)}</td></tr>) : <tr><td colSpan="4" className="table-message">No environments.</td></tr>}</tbody></table></div>) : <EmptyState title="No environments yet">Create a project first, then add production, staging, or another real environment.</EmptyState>}<EnvironmentForm open={open} onClose={() => setOpen(false)} projects={projects} onSaved={resource.refresh} /></Section></Page>
}

function EnvironmentForm({ open, onClose, projects, onSaved }) { const { organizationId } = useWorkspace(); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false); const available = useMemo(() => projects || [], [projects]); const submit = async (event) => { event.preventDefault(); setSubmitting(true); setError(''); const values = Object.fromEntries(new FormData(event.currentTarget)); const projectId = values.projectId; delete values.projectId; try { await api(organizationPath(organizationId, `/projects/${projectId}/environments`), { method: 'POST', body: values }); await onSaved(); onClose() } catch (requestError) { setError(requestError.message) } finally { setSubmitting(false) } }; return <Dialog title="Create environment" open={open} onClose={onClose}>{available.length ? <form className="form-stack" onSubmit={submit}><Field label="Project"><select name="projectId" required>{available.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Name"><input name="name" required /></Field><Field label="Slug"><input name="slug" /></Field><ErrorNotice error={error} /><SubmitRow submitting={submitting} onCancel={onClose} label="Create environment" /></form> : <EmptyState title="A project is required">Create a project before adding an environment.</EmptyState>}</Dialog> }

export function EnvironmentDetailPage() {
  const { organizationId } = useWorkspace(); const { environmentId } = useParams(); const navigate = useNavigate(); const [deleteOpen, setDeleteOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const resource = useResource(async () => { if (!organizationId) return null; const root = organizationPath(organizationId); const [environment, applications, deployments, domains] = await Promise.all([api(`${root}/environments/${environmentId}`), api(`${root}/environments/${environmentId}/applications`), api(`${root}/deployments`), api(`${root}/domains`).catch(() => ({ domains: [] }))]); const project = await api(`${root}/projects/${environment.projectId}`); const ids = new Set(applications.applications.map((item) => item.id)); return { environment, project, applications: applications.applications, deployments: deployments.deployments.filter((item) => ids.has(item.applicationId)), domains: domains.domains.filter((item) => ids.has(item.applicationId)) } }, [organizationId, environmentId])
  if (resource.loading) return <Page title="Environment" description="Loading workspace…" />
  if (resource.error) return <Page title="Environment"><ErrorNotice error={resource.error} /></Page>
  const { environment, project, applications, deployments, domains } = resource.data; const names = Object.fromEntries(applications.map((item) => [item.id, item.name]))
  const save = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { await api(organizationPath(organizationId, `/environments/${environmentId}`), { method: 'PUT', body: Object.fromEntries(new FormData(event.currentTarget)) }); await resource.refresh() } catch (requestError) { setError(requestError.message) } finally { setBusy(false) } }
  const remove = async () => { setBusy(true); setError(''); try { await api(organizationPath(organizationId, `/environments/${environmentId}`), { method: 'DELETE' }); navigate(`/projects/${project.id}`) } catch (requestError) { setError(requestError.message); setDeleteOpen(false) } finally { setBusy(false) } }
  return <Page title={environment.name} description={`${project.name} environment`}><WorkspaceNav items={[{ id: 'overview', label: 'Overview' }, { id: 'applications', label: 'Applications' }, { id: 'deployments', label: 'Deployments' }, { id: 'variables', label: 'Variables' }, { id: 'secrets', label: 'Secrets' }, { id: 'domains', label: 'Domains' }, { id: 'settings', label: 'Settings' }]} /><ErrorNotice error={error} />
    <div id="overview"><Section title="Overview"><dl className="definition-grid"><div><dt>Project</dt><dd><Link to={`/projects/${project.id}`}>{project.name}</Link></dd></div><div><dt>Slug</dt><dd><Mono>{environment.slug}</Mono></dd></div><div><dt>Applications</dt><dd>{applications.length}</dd></div><div><dt>Created</dt><dd>{formatDate(environment.createdAt)}</dd></div></dl></Section></div>
    <div id="applications"><Section title="Applications"><table><thead><tr><th>Name</th><th>Source</th><th>Internal port</th></tr></thead><tbody>{applications.length ? applications.map((item) => <tr key={item.id}><td><Link to={`/projects/${project.id}/applications/${item.id}`}>{item.name}</Link></td><td>{item.sourceType}</td><td><Mono>{item.internalPort ? `:${item.internalPort}` : '—'}</Mono></td></tr>) : <tr><td colSpan="3"><EmptyState title="No applications">Create an application from the project workspace.</EmptyState></td></tr>}</tbody></table></Section></div>
    <div id="deployments"><Section title="Deployments"><table><thead><tr><th>ID</th><th>Application</th><th>Status</th><th>Revision</th><th>Created</th></tr></thead><tbody>{deployments.length ? deployments.map((item) => <tr key={item.id}><td><Link to={`/deployments/${item.id}`}><Mono>#{item.number}</Mono></Link></td><td>{names[item.applicationId]}</td><td><Status value={item.status} /></td><td><Mono>{item.commitSha || item.sourceRevision || '—'}</Mono></td><td>{formatDate(item.createdAt)}</td></tr>) : <tr><td colSpan="5"><EmptyState title="No deployments yet">No application in this environment has been deployed.</EmptyState></td></tr>}</tbody></table></Section></div>
    <div id="configuration"><Section title="Variables & secrets" description="Overrides project defaults for every application in this environment."><ConfigurationEditor root={organizationPath(organizationId, `/environments/${environmentId}`)} inheritedRoot={organizationPath(organizationId, `/projects/${project.id}`)} inheritedLabel="Project" scopeLabel="Environment" /></Section></div>
    <div id="domains"><Section title="Domains"><table><thead><tr><th>Hostname</th><th>Application</th><th>Mode</th><th>State</th></tr></thead><tbody>{domains.length ? domains.map((item) => <tr key={item.id}><td>{item.hostname}</td><td>{names[item.applicationId]}</td><td>{item.routingMode?.replaceAll('_', ' ')}</td><td><Status value={item.dnsState} /></td></tr>) : <tr><td colSpan="4"><EmptyState title="No environment domains">Routes appear after they are attached to an application.</EmptyState></td></tr>}</tbody></table></Section></div>
    <div id="settings"><Section title="Settings"><form className="form-grid" onSubmit={save}><Field label="Name"><input name="name" defaultValue={environment.name} required /></Field><Field label="Slug"><input name="slug" defaultValue={environment.slug} required /></Field><div className="form-actions"><button className="button secondary" disabled={busy}>Save settings</button><button type="button" className="button danger" onClick={() => setDeleteOpen(true)}>Delete environment</button></div></form></Section></div>
    <ConfirmDeleteDialog open={deleteOpen} title="Delete environment" description="Silicon only deletes an environment after its applications are removed." confirmation={environment.slug} busy={busy} error={error} onClose={() => setDeleteOpen(false)} onConfirm={remove} />
  </Page>
}
