import { useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ArrowClockwiseIcon, LinkSimpleIcon, NetworkIcon, PlusIcon, ShieldCheckIcon, TrashIcon } from '@phosphor-icons/react'
import { api, organizationPath } from '../lib/api.js'
import { useWorkspace } from '../state/WorkspaceContext.jsx'
import { ConfirmDeleteDialog } from '../components/Workspace.jsx'
import { CreateButton, Dialog, EmptyState, ErrorNotice, Field, LoadingRows, Mono, Notice, Page, Section, Status, SubmitRow, formatDate, useResource } from '../components/ui.jsx'

export function NetworksPage() {
  const { organizationId } = useWorkspace()
  const [open, setOpen] = useState(false); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false)
  const resource = useResource(async () => {
    if (!organizationId) return { networks: [], servers: [] }
    const root = organizationPath(organizationId)
    const [networks, servers] = await Promise.all([api(`${root}/networks`), api(`${root}/servers`)])
    return { networks: networks.networks, servers: servers.servers.filter((server) => server.connectionStatus === 'connected' && server.dockerAvailable && ['local', 'ssh'].includes(server.connectionType)) }
  }, [organizationId])
  const create = async (event) => {
    event.preventDefault(); setSubmitting(true); setError('')
    const values = Object.fromEntries(new FormData(event.currentTarget)); values.listenPort = Number(values.listenPort)
    try { await api(organizationPath(organizationId, '/networks'), { method: 'POST', body: values }); setOpen(false); await resource.refresh() } catch (requestError) { setError(requestError.message) } finally { setSubmitting(false) }
  }
  return <Page title="Networks" description="Organization-private WireGuard overlays, internal service discovery, and explicit east-west policy." actions={<CreateButton disabled={!resource.data?.servers.length} onClick={() => setOpen(true)}>Create network</CreateButton>}>
    <ErrorNotice error={resource.error || error} />
    {!resource.loading && !resource.data?.servers.length && <Notice tone="warning">Connect at least one Docker-capable local or SSH server before creating a private network.</Notice>}
    <Section title="Private networks" description="Cloudflare remains public ingress. These networks carry private service-to-service traffic only.">
      <table><thead><tr><th>Name</th><th>CIDR</th><th>Provider</th><th>Topology</th><th>Status</th><th>Last reconciled</th></tr></thead><tbody>
        {resource.loading ? <LoadingRows columns={6} /> : resource.data.networks.length ? resource.data.networks.map((item) => <tr key={item.id}><td><Link className="table-link" to={`/networks/${item.id}`}><NetworkIcon size={16} /><span>{item.name}</span></Link></td><td><Mono>{item.cidr}</Mono></td><td>WireGuard</td><td>Hub and spoke</td><td><Status value={item.status} /></td><td>{formatDate(item.lastReconciledAt)}</td></tr>) : <tr><td colSpan="6"><EmptyState title="No private networks">Create an opt-in WireGuard overlay when applications need cross-server private connectivity.</EmptyState></td></tr>}
      </tbody></table>
    </Section>
    <Dialog title="Create private network" open={open} onClose={() => setOpen(false)}><form className="form-grid" onSubmit={create}><Field label="Name"><input name="name" placeholder="Production private" required /></Field><Field label="Private CIDR" hint="Canonical RFC1918 IPv4 range, /16 through /29. It must not overlap another Silicon network."><input className="mono" name="cidr" placeholder="10.44.0.0/24" required /></Field><Field label="Hub server" hint="The hub must have a reachable public address or DNS name for NATed spokes."><select name="hubServerId" required><option value="">Select server</option>{(resource.data?.servers || []).map((server) => <option key={server.id} value={server.id}>{server.name} · {server.connectionType.toUpperCase()}</option>)}</select></Field><Field label="WireGuard UDP port"><input className="mono" name="listenPort" type="number" min="1" max="65535" defaultValue="51820" required /></Field><SubmitRow submitting={submitting} onCancel={() => setOpen(false)} label="Create and reconcile" /></form></Dialog>
  </Page>
}

export function NetworkDetailPage() {
	const { networkId } = useParams(); const navigate = useNavigate(); const { organizationId } = useWorkspace(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [deleteOpen, setDeleteOpen] = useState(false)
  const resource = useResource(async () => {
    if (!organizationId) return null
    const root = organizationPath(organizationId); const [network, servers, applications] = await Promise.all([api(`${root}/networks/${networkId}`), api(`${root}/servers`), api(`${root}/applications`)])
    return { network: network.network, servers: servers.servers, applications: applications.applications }
  }, [organizationId, networkId])
  const run = async (work) => { setBusy(true); setError(''); try { await work(); await resource.refresh() } catch (requestError) { setError(requestError.message) } finally { setBusy(false) } }
  const network = resource.data?.network
  const availableServers = useMemo(() => (resource.data?.servers || []).filter((server) => server.connectionStatus === 'connected' && server.dockerAvailable && ['local', 'ssh'].includes(server.connectionType) && !network?.members.some((member) => member.serverId === server.id)), [resource.data?.servers, network?.members])
  const availableApps = useMemo(() => (resource.data?.applications || []).filter((app) => app.serverId && app.internalPort && network?.members.some((member) => member.serverId === app.serverId) && !network.services.some((service) => service.applicationId === app.id)), [resource.data?.applications, network?.members, network?.services])
  const addMember = (event) => { event.preventDefault(); const serverId = new FormData(event.currentTarget).get('serverId'); run(() => api(organizationPath(organizationId, `/networks/${networkId}/members`), { method: 'POST', body: { serverId } })) }
  const addService = (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); values.port = Number(values.port); run(() => api(organizationPath(organizationId, `/networks/${networkId}/services`), { method: 'POST', body: values })) }
  const addPolicy = (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); const service = network.services.find((item) => item.id === values.destinationServiceId); values.port = service?.port || 0; values.protocol = service?.protocol || 'tcp'; run(() => api(organizationPath(organizationId, `/networks/${networkId}/policies`), { method: 'POST', body: values })) }
	const remove = async () => { setBusy(true); setError(''); try { await api(organizationPath(organizationId, `/networks/${networkId}`), { method: 'DELETE' }); navigate('/networks') } catch (requestError) { setError(requestError.message); setDeleteOpen(false) } finally { setBusy(false) } }
  if (resource.loading || !network) return <Page title="Network"><div role="status">Loading network…</div><ErrorNotice error={resource.error} /></Page>
	return <Page title={network.name} description="WireGuard hub-and-spoke overlay with Silicon-managed internal DNS and least-privilege policy." actions={<><button className="button secondary" disabled={busy} onClick={() => run(() => api(organizationPath(organizationId, `/networks/${networkId}/reconcile`), { method: 'POST' }))}><ArrowClockwiseIcon size={16} /><span>Reconcile</span></button><button className="button danger" disabled={busy || network.services.length > 0} onClick={() => setDeleteOpen(true)}><TrashIcon size={16} /><span>Delete network</span></button></>}>
    <ErrorNotice error={resource.error || error} />
    <Section title="Network state"><div className="definition-grid"><div><span>Status</span><Status value={network.status} /></div><div><span>CIDR</span><Mono>{network.cidr}</Mono></div><div><span>Provider</span><strong>WireGuard</strong></div><div><span>Topology</span><strong>Hub and spoke</strong></div><div><span>Listen port</span><Mono>{network.listenPort}/udp</Mono></div><div><span>Last reconciled</span><strong>{formatDate(network.lastReconciledAt)}</strong></div></div>{network.lastError && <Notice tone="danger">{network.lastError}</Notice>}</Section>
    <Section title="Members" description="Keys are generated and retained on each host. Silicon stores public keys only." actions={availableServers.length ? <form className="inline-form" onSubmit={addMember}><select name="serverId" aria-label="Server to add">{availableServers.map((server) => <option key={server.id} value={server.id}>{server.name} · {server.connectionType}</option>)}</select><button className="button secondary compact" disabled={busy}><PlusIcon size={16} /><span>Add server</span></button></form> : null}>
      <table><thead><tr><th>Server</th><th>Connection</th><th>Overlay address</th><th>Role</th><th>Status</th><th></th></tr></thead><tbody>{network.members.map((member) => <tr key={member.id}><td>{member.serverName}</td><td>{member.connectionType.toUpperCase()}</td><td><Mono>{member.address}</Mono></td><td>{member.serverId === network.hubServerId ? 'Hub' : 'Spoke'}</td><td><Status value={member.status} /></td><td>{member.serverId !== network.hubServerId && <button className="button ghost compact" disabled={busy || network.services.some((service) => service.serverId === member.serverId)} onClick={() => run(() => api(organizationPath(organizationId, `/networks/${networkId}/members/${member.id}`), { method: 'DELETE' }))}><TrashIcon size={15} /><span>Remove</span></button>}</td></tr>)}</tbody></table>
    </Section>
    <Section title="Service discovery" description="Names resolve only inside attached workloads. The target port is published on the server's overlay address, never on 0.0.0.0.">
      {availableApps.length > 0 && <form className="form-grid compact-form" onSubmit={addService}><Field label="Application"><select name="applicationId">{availableApps.map((app) => <option key={app.id} value={app.id}>{app.name} · port {app.internalPort}</option>)}</select></Field><Field label="Internal hostname" hint="Leave empty for app.environment.project.internal."><input name="hostname" placeholder="backend.production.shop.internal" /></Field><Field label="Protocol"><select name="protocol"><option value="tcp">TCP</option><option value="udp">UDP</option></select></Field><Field label="Service port"><input name="port" type="number" min="1" max="65535" defaultValue={availableApps[0]?.internalPort || 3000} required /></Field><div className="form-actions"><button className="button secondary" disabled={busy}><LinkSimpleIcon size={16} /><span>Attach service</span></button></div></form>}
      <table><thead><tr><th>Name</th><th>Application</th><th>Project</th><th>Endpoint</th><th>Status</th><th></th></tr></thead><tbody>{network.services.length ? network.services.map((service) => <tr key={service.id}><td><Mono>{service.hostname}</Mono></td><td>{service.application}</td><td>{service.project}</td><td><Mono>{service.protocol} :{service.port}</Mono></td><td><Status value={service.status} /></td><td><button className="button ghost compact" disabled={busy} onClick={() => run(() => api(organizationPath(organizationId, `/networks/${networkId}/services/${service.id}`), { method: 'DELETE' }))}><TrashIcon size={15} /><span>Detach</span></button></td></tr>) : <tr><td colSpan="6"><EmptyState title="No attached services">Attach an application after its target server joins this network.</EmptyState></td></tr>}</tbody></table>
    </Section>
    <Section title="Access policies" description="Same-project traffic is allowed by default. Cross-project traffic is denied unless an explicit allow policy matches.">
      {network.services.length > 0 && <form className="form-grid compact-form" onSubmit={addPolicy}><Field label="Policy name"><input name="name" placeholder="frontend-to-api" required /></Field><Field label="Source application"><select name="sourceApplicationId">{network.services.map((service) => <option key={service.applicationId} value={service.applicationId}>{service.application} · {service.project}</option>)}</select></Field><Field label="Destination service"><select name="destinationServiceId">{network.services.map((service) => <option key={service.id} value={service.id}>{service.hostname} · {service.protocol}/{service.port}</option>)}</select></Field><Field label="Action"><select name="action"><option value="allow">Allow</option><option value="deny">Deny</option></select></Field><div className="form-actions"><button className="button secondary" disabled={busy}><ShieldCheckIcon size={16} /><span>Add policy</span></button></div></form>}
      <table><thead><tr><th>Policy</th><th>Source application</th><th>Destination</th><th>Rule</th><th></th></tr></thead><tbody>{network.policies.length ? network.policies.map((policy) => <tr key={policy.id}><td>{policy.name}</td><td>{policy.sourceApplication}</td><td><Mono>{policy.destinationHostname}</Mono></td><td>{policy.action.toUpperCase()} <Mono>{policy.protocol}/{policy.port}</Mono></td><td><button className="button ghost compact" disabled={busy} onClick={() => run(() => api(organizationPath(organizationId, `/networks/${networkId}/policies/${policy.id}`), { method: 'DELETE' }))}><TrashIcon size={15} /><span>Delete</span></button></td></tr>) : <tr><td colSpan="5"><EmptyState title="No explicit policies">Only same-project traffic is allowed.</EmptyState></td></tr>}</tbody></table>
    </Section>
    <Section title="Reconciliation"><table><thead><tr><th>Operation</th><th>Status</th><th>Started</th><th>Result</th></tr></thead><tbody>{network.operations.map((operation) => <tr key={operation.id}><td>{operation.operationType}</td><td><Status value={operation.status} /></td><td>{formatDate(operation.createdAt)}</td><td>{operation.error || '—'}</td></tr>)}</tbody></table></Section>
		<ConfirmDeleteDialog open={deleteOpen} title="Delete private network" description="Silicon will asynchronously remove its WireGuard interfaces, DNS container, and owned firewall table from every member. Detach all application services first." confirmation={network.name} busy={busy} error={error} onClose={() => setDeleteOpen(false)} onConfirm={remove} />
  </Page>
}
