import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api, organizationPath } from '../lib/api.js'
import { useWorkspace } from '../state/WorkspaceContext.jsx'
import { Dialog, EmptyState, ErrorNotice, Field, LoadingRows, Page, Section, SubmitRow, formatDate, useResource } from '../components/ui.jsx'

export function ProjectsPage(){const {organizationId}=useWorkspace();const [open,setOpen]=useState(false);const resource=useResource(()=>organizationId?api(organizationPath(organizationId,'/projects')):Promise.resolve({projects:[]}),[organizationId]);return <Page title="Projects" description="Group related environments and applications." actions={organizationId&&<button className="button primary" onClick={()=>setOpen(true)}>Create project</button>}><ErrorNotice error={resource.error}/><Section title="All projects"><table><thead><tr><th>Name</th><th>Slug</th><th>Description</th><th>Created</th></tr></thead><tbody>{resource.loading?<LoadingRows/>:resource.data?.projects.length?resource.data.projects.map(item=><tr key={item.id}><td data-label="Name"><Link to={`/projects/${item.id}`}>{item.name}</Link></td><td data-label="Slug" className="mono">{item.slug}</td><td data-label="Description">{item.description||'—'}</td><td data-label="Created">{formatDate(item.createdAt)}</td></tr>):<tr><td colSpan="4"><EmptyState title="No projects yet">Create a project to group environments and applications.</EmptyState></td></tr>}</tbody></table><ProjectForm open={open} onClose={()=>setOpen(false)} onSaved={resource.refresh}/></Section></Page>}

function ProjectForm({open,onClose,onSaved}){const {organizationId}=useWorkspace();const [error,setError]=useState('');const [submitting,setSubmitting]=useState(false);const submit=async(event)=>{event.preventDefault();setSubmitting(true);setError('');try{await api(organizationPath(organizationId,'/projects'),{method:'POST',body:Object.fromEntries(new FormData(event.currentTarget))});await onSaved();onClose()}catch(requestError){setError(requestError.message)}finally{setSubmitting(false)}};return <Dialog title="Create project" open={open} onClose={onClose}><form className="form-stack" onSubmit={submit}><Field label="Name"><input name="name" required/></Field><Field label="Slug" hint="Optional; generated from the name when omitted."><input name="slug"/></Field><Field label="Description"><textarea name="description" rows="3"/></Field><ErrorNotice error={error}/><SubmitRow submitting={submitting} onCancel={onClose} label="Create project"/></form></Dialog>}

export function ProjectDetailPage(){const {organizationId}=useWorkspace();const {projectId}=useParams();const resource=useResource(async()=>{if(!organizationId)return null;const [project,environments]=await Promise.all([api(organizationPath(organizationId,`/projects/${projectId}`)),api(organizationPath(organizationId,`/projects/${projectId}/environments`))]);return {project,environments:environments.environments}},[organizationId,projectId]);if(resource.loading)return <Page title="Project" description="Loading…"/>;if(resource.error)return <Page title="Project"><ErrorNotice error={resource.error}/></Page>;const {project,environments}=resource.data;return <Page title={project.name} description={project.description||'No project description.'}><Section title="Overview"><dl className="definition-grid"><div><dt>Slug</dt><dd className="mono">{project.slug}</dd></div><div><dt>Project ID</dt><dd className="mono">{project.id}</dd></div><div><dt>Created</dt><dd>{formatDate(project.createdAt)}</dd></div><div><dt>Updated</dt><dd>{formatDate(project.updatedAt)}</dd></div></dl></Section><Section title="Environments" description="Environment-specific configuration and applications."><table><thead><tr><th>Name</th><th>Slug</th><th>Created</th></tr></thead><tbody>{environments.length?environments.map(item=><tr key={item.id}><td data-label="Name">{item.name}</td><td data-label="Slug" className="mono">{item.slug}</td><td data-label="Created">{formatDate(item.createdAt)}</td></tr>):<tr><td colSpan="3" className="table-message">No environments in this project.</td></tr>}</tbody></table></Section><Section title="Settings" description="Project mutations are enforced by permission at the API boundary."><p className="muted">Edit and deletion endpoints are available in the API. Destructive UI controls are intentionally omitted until confirmation workflows are added.</p></Section></Page>}
