import { useMemo, useState } from 'react'
import { GearIcon } from '@phosphor-icons/react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api, organizationPath } from '../lib/api.js'
import { useWorkspace } from '../state/WorkspaceContext.jsx'
import { ConfigurationEditor, ConfirmDeleteDialog, WorkspaceNav } from '../components/Workspace.jsx'
import { ApplicationSourceFields, PortBindingFields, RuntimeTargetField } from '../components/ApplicationFields.jsx'
import { applicationFormValues } from '../lib/application-form.js'
import { CreateButton, Dialog, EmptyState, ErrorNotice, Field, LoadingRows, Mono, Page, Section, Status, SubmitRow, formatDate, useResource } from '../components/ui.jsx'

export function ProjectsPage() {
  const { organizationId } = useWorkspace(); const [open, setOpen] = useState(false)
  const resource = useResource(() => organizationId ? api(organizationPath(organizationId, '/projects')) : Promise.resolve({ projects: [] }), [organizationId])
  return <Page title="Projects" description="Workspaces for related environments, applications, configuration, and delivery history." actions={organizationId && <CreateButton onClick={() => setOpen(true)}>Create project</CreateButton>}><ErrorNotice error={resource.error} /><Section title="All projects"><table><thead><tr><th>Name</th><th>Slug</th><th>Description</th><th>Created</th></tr></thead><tbody>{resource.loading ? <LoadingRows /> : resource.data?.projects.length ? resource.data.projects.map((item) => <tr key={item.id}><td><Link to={`/projects/${item.id}`}>{item.name}</Link></td><td><Mono>{item.slug}</Mono></td><td>{item.description || '—'}</td><td>{formatDate(item.createdAt)}</td></tr>) : <tr><td colSpan="4"><EmptyState title="No projects yet">Create a project to group environments and applications.</EmptyState></td></tr>}</tbody></table><ProjectForm open={open} onClose={() => setOpen(false)} onSaved={resource.refresh} /></Section></Page>
}

function ProjectForm({ open, onClose, onSaved }) {
  const { organizationId } = useWorkspace(); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false)
  const submit = async (event) => { event.preventDefault(); setSubmitting(true); setError(''); try { await api(organizationPath(organizationId, '/projects'), { method: 'POST', body: Object.fromEntries(new FormData(event.currentTarget)) }); await onSaved(); onClose() } catch (requestError) { setError(requestError.message) } finally { setSubmitting(false) } }
  return <Dialog title="Create project" open={open} onClose={onClose}><form className="form-stack" onSubmit={submit}><Field label="Name"><input name="name" required /></Field><Field label="Slug" hint="Optional; generated from the name when omitted."><input name="slug" /></Field><Field label="Description"><textarea name="description" rows="3" /></Field><ErrorNotice error={error} /><SubmitRow submitting={submitting} onCancel={onClose} label="Create project" /></form></Dialog>
}

export function ProjectDetailPage() {
  const { organizationId } = useWorkspace(); const { projectId } = useParams(); const navigate = useNavigate()
  const [environmentOpen, setEnvironmentOpen] = useState(false); const [applicationOpen, setApplicationOpen] = useState(false); const [deleteOpen, setDeleteOpen] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const resource = useResource(async () => {
    if (!organizationId) return null
    const root = organizationPath(organizationId)
    const [project, environments, applications, deployments, domains, targets, networkList] = await Promise.all([api(`${root}/projects/${projectId}`), api(`${root}/projects/${projectId}/environments`), api(`${root}/applications`), api(`${root}/deployments`), api(`${root}/domains`).catch(() => ({ domains: [] })), api(`${root}/servers`), api(`${root}/networks`)])
    const projectApplications = applications.applications.filter((item) => item.projectId === projectId); const applicationIds = new Set(projectApplications.map((item) => item.id))
    const networkDetails = await Promise.all(networkList.networks.map((item) => api(`${root}/networks/${item.id}`)))
    const networkServices = networkDetails.flatMap(({ network }) => network.services.filter((service) => service.projectId === projectId).map((service) => ({ ...service, networkId: network.id, networkName: network.name, outboundPolicies: network.policies.filter((policy) => policy.sourceApplicationId === service.applicationId).length, inboundPolicies: network.policies.filter((policy) => policy.destinationServiceId === service.id).length })))
    return { project, environments: environments.environments, applications: projectApplications, deployments: deployments.deployments.filter((item) => applicationIds.has(item.applicationId)), domains: domains.domains.filter((item) => applicationIds.has(item.applicationId)), networkServices, servers: targets.servers, localRuntimeAvailable: targets.localRuntimeAvailable === true }
  }, [organizationId, projectId])
  if (resource.loading) return <Page title="Project" description="Loading workspace…" />
  if (resource.error) return <Page title="Project"><ErrorNotice error={resource.error} /></Page>
  const { project, environments, applications, deployments, domains, networkServices, servers, localRuntimeAvailable } = resource.data
  const applicationNames = Object.fromEntries(applications.map((item) => [item.id, item.name])); const serverNames = Object.fromEntries(servers.map((item) => [item.id, item.name]))
  const save = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { await api(organizationPath(organizationId, `/projects/${projectId}`), { method: 'PUT', body: Object.fromEntries(new FormData(event.currentTarget)) }); await resource.refresh() } catch (requestError) { setError(requestError.message) } finally { setBusy(false) } }
  const remove = async () => { setBusy(true); setError(''); try { await api(organizationPath(organizationId, `/projects/${projectId}`), { method: 'DELETE' }); navigate('/projects') } catch (requestError) { setError(requestError.message); setDeleteOpen(false) } finally { setBusy(false) } }
  return <Page title={project.name} description={project.description || 'Project workspace'} actions={<><button className="button secondary" onClick={() => setEnvironmentOpen(true)}>Add environment</button><CreateButton onClick={() => setApplicationOpen(true)}>Create application</CreateButton></>}>
    <WorkspaceNav items={[{ id: 'overview', label: 'Overview' }, { id: 'environments', label: 'Environments' }, { id: 'applications', label: 'Applications' }, { id: 'deployments', label: 'Deployments' }, { id: 'variables', label: 'Variables' }, { id: 'secrets', label: 'Secrets' }, { id: 'networking', label: 'Networking' }, { id: 'domains', label: 'Domains' }, { id: 'settings', label: 'Settings' }]} /><ErrorNotice error={error} />
    <div id="overview"><Section title="Overview"><dl className="definition-grid"><div><dt>Slug</dt><dd><Mono>{project.slug}</Mono></dd></div><div><dt>Project ID</dt><dd><Mono>{project.id}</Mono></dd></div><div><dt>Environments</dt><dd>{environments.length}</dd></div><div><dt>Applications</dt><dd>{applications.length}</dd></div><div><dt>Created</dt><dd>{formatDate(project.createdAt)}</dd></div><div><dt>Updated</dt><dd>{formatDate(project.updatedAt)}</dd></div></dl></Section></div>
    <div id="environments"><Section title="Environments" description="Configuration boundaries within this project."><table><thead><tr><th>Name</th><th>Slug</th><th>Applications</th><th>Created</th></tr></thead><tbody>{environments.length ? environments.map((item) => <tr key={item.id}><td><Link to={`/projects/${projectId}/environments/${item.id}`}>{item.name}</Link></td><td><Mono>{item.slug}</Mono></td><td>{applications.filter((application) => application.environmentId === item.id).length}</td><td>{formatDate(item.createdAt)}</td></tr>) : <tr><td colSpan="4"><EmptyState title="No environments">Add production, staging, or another real environment.</EmptyState></td></tr>}</tbody></table></Section></div>
    <div id="applications"><Section title="Applications" description="Deployable workloads grouped by environment.">{environments.length ? environments.map((environment) => <div className="resource-group" key={environment.id}><h3>{environment.name}</h3><table><thead><tr><th>Name</th><th>State</th><th>Source</th><th>Target</th><th>Port</th></tr></thead><tbody>{applications.filter((item) => item.environmentId === environment.id).length ? applications.filter((item) => item.environmentId === environment.id).map((item) => { const latest = deployments.find((deployment) => deployment.applicationId === item.id); return <tr key={item.id}><td><Link to={`/projects/${projectId}/applications/${item.id}`}>{item.name}</Link></td><td>{latest ? <Status value={latest.status} /> : <span className="muted">Not deployed</span>}</td><td>{item.sourceType}</td><td>{item.serverId ? serverNames[item.serverId] || 'Unknown server' : 'Local Silicon host'}</td><td><Mono>{item.internalPort ? `:${item.internalPort}` : '—'}</Mono></td></tr> }) : <tr><td colSpan="5" className="table-message">No applications in this environment.</td></tr>}</tbody></table></div>) : <EmptyState title="Create an environment first">Applications always belong to one environment.</EmptyState>}</Section></div>
    <div id="deployments"><Section title="Recent deployments"><table><thead><tr><th>ID</th><th>Application</th><th>Status</th><th>Trigger</th><th>Revision</th><th>Created</th></tr></thead><tbody>{deployments.length ? deployments.slice(0, 12).map((item) => <tr key={item.id}><td><Link to={`/deployments/${item.id}`}><Mono>#{item.number}</Mono></Link></td><td>{applicationNames[item.applicationId]}</td><td><Status value={item.status} /></td><td>{item.triggerType}</td><td><Mono>{item.commitSha || item.sourceRevision || '—'}</Mono></td><td>{formatDate(item.createdAt)}</td></tr>) : <tr><td colSpan="6"><EmptyState title="No deployments yet">Deploy from an application workspace when a runtime target is configured.</EmptyState></td></tr>}</tbody></table></Section></div>
    <div id="configuration"><Section title="Variables & secrets" description="Project defaults are inherited by every application unless overridden."><ConfigurationEditor root={organizationPath(organizationId, `/projects/${projectId}`)} scopeLabel="Project" /></Section></div>
    <div id="networking"><Section title="Private networking" description="Project services attached to organization-private overlays."><table><thead><tr><th>Network</th><th>Application</th><th>Service name</th><th>Endpoint</th><th>Policy state</th><th>Status</th></tr></thead><tbody>{networkServices.length ? networkServices.map((service) => <tr key={service.id}><td><Link to={`/networks/${service.networkId}`}>{service.networkName}</Link></td><td>{service.application}</td><td><Mono>{service.hostname}</Mono></td><td><Mono>{service.protocol} :{service.port}</Mono></td><td>{service.outboundPolicies} outbound · {service.inboundPolicies} inbound</td><td><Status value={service.status} /></td></tr>) : <tr><td colSpan="6"><EmptyState title="No private services">Attach a project application from Networks after its target server joins an overlay.</EmptyState></td></tr>}</tbody></table></Section></div>
    <div id="domains"><Section title="Domains" description="Routes attached to applications in this project."><table><thead><tr><th>Hostname</th><th>Application</th><th>Mode</th><th>State</th></tr></thead><tbody>{domains.length ? domains.map((item) => <tr key={item.id}><td>{item.hostname}</td><td>{applicationNames[item.applicationId]}</td><td>{item.routingMode?.replaceAll('_', ' ')}</td><td><Status value={item.dnsState} /></td></tr>) : <tr><td colSpan="4"><EmptyState title="No project domains">Domains appear here when attached to a project application.</EmptyState></td></tr>}</tbody></table></Section></div>
    <div id="settings"><Section title="Settings" description="Update project metadata or permanently remove this workspace."><form className="form-grid" onSubmit={save}><Field label="Name"><input name="name" defaultValue={project.name} required /></Field><Field label="Slug"><input name="slug" defaultValue={project.slug} required /></Field><Field label="Description"><input name="description" defaultValue={project.description} /></Field><div className="form-actions"><button className="button secondary" disabled={busy}><GearIcon size={16} /><span>Save settings</span></button><button className="button danger" type="button" onClick={() => setDeleteOpen(true)}>Delete project</button></div></form></Section></div>
    <EnvironmentCreateDialog open={environmentOpen} projectId={projectId} onClose={() => setEnvironmentOpen(false)} onSaved={resource.refresh} /><ApplicationCreateDialog open={applicationOpen} environments={environments} servers={servers} localRuntimeAvailable={localRuntimeAvailable} onClose={() => setApplicationOpen(false)} onSaved={resource.refresh} /><ConfirmDeleteDialog open={deleteOpen} title="Delete project" description="This permanently removes the project and its environments, applications, deployments, configuration, and routes." confirmation={project.slug} busy={busy} error={error} onClose={() => setDeleteOpen(false)} onConfirm={remove} />
  </Page>
}

function EnvironmentCreateDialog({ open, projectId, onClose, onSaved }) { const { organizationId } = useWorkspace(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { await api(organizationPath(organizationId, `/projects/${projectId}/environments`), { method: 'POST', body: Object.fromEntries(new FormData(event.currentTarget)) }); await onSaved(); onClose() } catch (requestError) { setError(requestError.message) } finally { setBusy(false) } }; return <Dialog open={open} title="Add environment" onClose={onClose}><form className="form-stack" onSubmit={submit}><Field label="Name"><input name="name" required /></Field><Field label="Slug"><input name="slug" /></Field><ErrorNotice error={error} /><SubmitRow submitting={busy} onCancel={onClose} label="Add environment" /></form></Dialog> }

function ApplicationCreateDialog({ open, environments, servers, localRuntimeAvailable, onClose, onSaved }) { const { organizationId } = useWorkspace(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const available = useMemo(() => environments || [], [environments]); const submit = async (event) => { event.preventDefault(); setError(''); const environmentId = new FormData(event.currentTarget).get('environmentId'); const result = applicationFormValues(event.currentTarget, { localRuntimeAvailable, servers }); delete result.values.environmentId; if (result.error) { setError(result.error); return } setBusy(true); try { await api(organizationPath(organizationId, `/environments/${environmentId}/applications`), { method: 'POST', body: result.values }); await onSaved(); onClose() } catch (requestError) { setError(requestError.message) } finally { setBusy(false) } }; return <Dialog open={open} title="Create application" onClose={onClose}>{available.length ? <form className="form-stack" onSubmit={submit}><Field label="Environment"><select name="environmentId">{available.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Name"><input name="name" required /></Field><ApplicationSourceFields key={open ? 'open' : 'closed'} /><RuntimeTargetField servers={servers} localRuntimeAvailable={localRuntimeAvailable} /><PortBindingFields key={open ? 'open' : 'closed'} /><ErrorNotice error={error} /><SubmitRow submitting={busy} onCancel={onClose} label="Create application" /></form> : <EmptyState title="An environment is required">Add an environment before creating an application.</EmptyState>}</Dialog> }
